name: musicdownloader
version: 1.0.1-beta.2
description: "通过Flutter重写的音乐下载器。"
repository: "https://github.com/MeoProject/musicdownloader"
issue_tracker: "https://github.com/MeoProject/musicdownloader/issues"
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  file_picker: ^5.3.1
  dio: ^5.7.0
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  http: ^0.13.5
  mime: ^2.0.0
  provider: ^6.1.2
  logger: ^2.5.0
  flutter_markdown: ^0.7.5
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.10
  path: ^1.8.0
  dynamic_color: ^1.7.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
  fonts:
    - family: LXGW Wenkai Mono GB Screen
      fonts:
        - asset: fonts/LXGWWenKaiMonoGBScreen.ttf
          weight: 700